apiVersion: apps/v1
kind: Deployment
metadata:
   name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      name: simple-app
      labels:
        app: python-app
    spec:
      containers:
        - name: simple-app
          image: gcr.io/global-memento-332706/jenkins-assignment:v1
         
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: LoadBalancer
  selector:
    app: simple-app
  ports:
   - name: http 
     port: 9000
     targetPort: 9000
   - name: metrics
     port: 8002
     targetPort: 8002
