apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: 
  selector:
    app: simple-app
  ports:
   - name: http 
     port: 9000
     targetPort: 9000
     protocol: HTTP
   - name: metrics
     port: 8002
     targetPort: 8002
     protocol: HTTP
